# Generated by Django 4.2.17 on 2025-02-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodoctimagemodel',
            name='file',
            field=models.ImageField(upload_to='product/extra-img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(default='/default/product-image.jpg', upload_to='product/img/%Y/%m/%d/'),
        ),
    ]
