# Generated by Django 4.2.17 on 2025-02-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_prodoctimagemodel_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='brief_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
